### Register User
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "h1@gmail.com",
  "password": "1"
}

### Login User
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "h1@gmail.com",
  "password": "1"
}

### Get /protected after login (use Cookie from Set-Cookie)
GET http://localhost:3000/protected
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmMTc1NTYzLTgwZmQtNDYyYi1hZTU5LTE3M2VjYjRiODdmNSIsImVtYWlsIjoiaDFAZ21haWwuY29tIiwiaWF0IjoxNzYwNzU5Mjk0LCJleHAiOjE3NjA3NjAxOTR9.JcBi-iv6jqVeeCts6Tk9_3ilBs0mQ37ZxMfwcvgXFg0

### Get All Documents (use Cookie from Set-Cookie)
GET http://localhost:3000/api/db/document/get-all

### get info user ()
GET http://localhost:3000/api/auth/me
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0NGQzZWVmLTM2ZDAtNGI4OS05NmZkLWZhNWM4ZmZiYTQ3NSIsImV4cCI6MTc2MDk2NTMwMywiaWF0IjoxNzYwOTY0NDAzLCJuYmYiOjE3NjA5NjQ0MDN9.ccrP1sFkkfTGx93vJyDJXWHNh1rgLuTt-4A3I0xkpJ0

### create new doc
POST http://localhost:3000/api/db/document/create
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4ZGQ0MzdmLWFlZGQtNDk2MS05YzQyLTk4NmVlNGIxMDU4MCIsImV4cCI6MTc2MTAxNTIyMSwiaWF0IjoxNzYxMDE0MzIxLCJuYmYiOjE3NjEwMTQzMjF9.IoOELdDLP78F7JOCmGtKFYhJELzju_-G3mUf0wavRco
Content-Type: application/json

{
  "title": "hhhhh",
  "initialContent": "",
  "organizationId":""
}































