import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TokenRefreshProvider } from "@/components/token-refresh-provider";
import { Toaster } from "@/components/ui/sonner";

import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";

import Providers from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={inter.className}
      >

        <NuqsAdapter>
          <TokenRefreshProvider>
            <Providers>
              <Toaster />
              {children}
            </Providers>
          </TokenRefreshProvider>
        </NuqsAdapter>

      </body>
    </html>
  );
}
