### Variables
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4ZGQ0MzdmLWFlZGQtNDk2MS05YzQyLTk4NmVlNGIxMDU4MCIsImV4cCI6MTc2MTI3MjQwNiwiaWF0IjoxNzYxMjcxNTA2LCJuYmYiOjE3NjEyNzE1MDZ9.0P0Vm-NPtBLzrohD9EihBu9qy95p4zR2zSIm7sciyOM

### get document theo  query pragram organizationId and search 
GET  {{baseUrl}}/api/db/document/?search=o
Cookie: access_token={{accessToken}}
Content-Type: application/json

### create new document by organization id
POST  {{baseUrl}}/api/db/document
Cookie: access_token={{accessToken}}
Content-Type: application/json

{ 
    "title":"test api create", 
    "initialContent":"", 
    "organizationId":"319b97ca-67f2-46b8-a978-7b906073667d" 
}

### test params 
GET  {{baseUrl}}/api/db/document/1234
Cookie: access_token={{accessToken}}
Content-Type: application/json

### test deleute document
DELETE  {{baseUrl}}/api/db/document/6aa2d892-58c2-4505-b03b-102a3c1cbd11
Cookie: access_token={{accessToken}}
Content-Type: application/json


### update db
PUT {{baseUrl}}/api/db/document/a3162c38-12b2-43ce-925e-32291f555d3a
Cookie: access_token={{accessToken}}
Content-Type: application/json

{
    "updated":{
        "title":"Blank Document 1223"
    }
}



